config/routes.rb
Rails.application.routes.draw do
namespace :api do
  resources :todo_lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

 	resources :monkeys
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monkey.rb
class Monkey < ApplicationRecord
end

app/controllers/api/todo_lists_controller.rb
class Api::TodoListsController < ApplicationController
	def index
		render json: Monkey.all
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/monkeys_controller.rb
class MonkeysController < ApplicationController
  before_action :set_monkey, only: [:show, :edit, :update, :destroy]

  # GET /monkeys
  # GET /monkeys.json
  def index
    @monkeys = Monkey.all
  end

  # GET /monkeys/1
  # GET /monkeys/1.json
  def show
  end

  # GET /monkeys/new
  def new
    @monkey = Monkey.new
  end

  # GET /monkeys/1/edit
  def edit
  end

  # POST /monkeys
  # POST /monkeys.json
  def create
    @monkey = Monkey.new(monkey_params)

    respond_to do |format|
      if @monkey.save
        format.html { redirect_to @monkey, notice: 'Monkey was successfully created.' }
        format.json { render :show, status: :created, location: @monkey }
      else
        format.html { render :new }
        format.json { render json: @monkey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monkeys/1
  # PATCH/PUT /monkeys/1.json
  def update
    respond_to do |format|
      if @monkey.update(monkey_params)
        format.html { redirect_to @monkey, notice: 'Monkey was successfully updated.' }
        format.json { render :show, status: :ok, location: @monkey }
      else
        format.html { render :edit }
        format.json { render json: @monkey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monkeys/1
  # DELETE /monkeys/1.json
  def destroy
    @monkey.destroy
    respond_to do |format|
      format.html { redirect_to monkeys_url, notice: 'Monkey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monkey
      @monkey = Monkey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monkey_params
      params.fetch(:monkey, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monkeys_helper.rb
module MonkeysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonkeyingAround</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monkeys/_form.html.erb
<%= form_for(monkey) do |f| %>
  <% if monkey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monkey.errors.count, "error") %> prohibited this monkey from being saved:</h2>

      <ul>
      <% monkey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monkeys/edit.html.erb
<h1>Editing Monkey</h1>

<%= render 'form', monkey: @monkey %>

<%= link_to 'Show', @monkey %> |
<%= link_to 'Back', monkeys_path %>

app/views/monkeys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monkeys</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monkeys.each do |monkey| %>
      <tr>
        <td><%= link_to 'Show', monkey %></td>
        <td><%= link_to 'Edit', edit_monkey_path(monkey) %></td>
        <td><%= link_to 'Destroy', monkey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monkey', new_monkey_path %>

app/views/monkeys/new.html.erb
<h1>New Monkey</h1>

<%= render 'form', monkey: @monkey %>

<%= link_to 'Back', monkeys_path %>

app/views/monkeys/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_monkey_path(@monkey) %> |
<%= link_to 'Back', monkeys_path %>